spring:
  application:
    name: name

  datasource:
    url: jdbc:mysql://localhost:3307/mydb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: user
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration



firebase:
  service-account-path: ./service_key.json