spring:
  application:
    name: name

  datasource:
    url: jdbc:mysql://localhost:3307/mydb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: user
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  cors:
    allowed-origins: http://localhost:*,https://localhost:*,http://127.0.0.1:*,https://127.0.0.1:*,http://d2z3q2wfhh6j6x.cloudfront.net,https://d2z3q2wfhh6j6x.cloudfront.net
